### ISSUE TITLE
[1.9.1] Docking Camera replaces main view

### ISSUE THREAD

**Issue by swavkulinski** [linuxgurugamer/DockingCam#9] opened 2020-04-12 17:11 UTC
Hi,

in 1.9.1

when turning Docking Camera on from the part menu it replaces the entire screen with the view of the part (docking port). Everything else is not rendered. Docking Camera view is displayed as well and it seems to work (shows params etc). However it doesn't have a frame as it used to have.

Installed Mods
==

000_ClickThroughBlocker
001_ToolbarControl
Ablative-Airbrake
AirplanePlus
B9PartSwitch
B9_Aerospace_ProceduralWings
BasicProceduralTextures
Benjee10_sharedAssets
BetterBurnTime
CommunityResourcePack
DecouplerShroud
DockingCamKURS
DynamicBatteryStorage
Firespitter
HabTech2
HeatControl
Interkosmos
KerbalEngineer
KerbalJointReinforcement
NearFutureElectrical
NearFuturePropulsion
NearFutureSolar
ProceduralParts
QuizTechAeroContinued
REPOSoftTech
Tantares
TantaresLV
ThunderAerospace
TokamakIndustries
WildBlueIndustries
WorldStabilizer

**Comment by linuxgurugamer** [comment] 2020-04-12 17:13
It's a known issue, look at the forum thread.  It is being looked into, but no idea when it will be fixed.

**Comment by dangros** [comment] 2020-05-21 23:49
is there a way @dennyTX can start a branch so we can see potential progress?

**Comment by linuxgurugamer** [comment] 2020-05-22 21:54
He has been AFK for a long time now.  I have no idea what, if anything, is going on

**Comment by dangros** [comment] 2020-05-23 00:29
I love this mod and am a c# dev.  Would love to take a crack at it but not sure how feasible it is given I’ve never coded gaming stuff or even pulled any Kerbal code.

**Comment by KSP-TaxiService** [comment] 2020-08-02 14:31
Hi @linuxgurugamer,

The root cause of this issue in 1.9.x and 1.10.x is the renaming of KSP's main camera from "Camera 01" to "UIMainCamera".
As such, the mod could not retrieve the main camera reference, resulting in this issue.

This change in [`BaseCamera.cs`](https://github.com/linuxgurugamer/DockingCam/blob/master/Source/Camera/BaseCamera.cs#L72) is sufficient to restore this mod to its glory.
From
`protected List<string> CameraNames = new List<string> { "GalaxyCamera", "Camera ScaledSpace", "Camera 01", "Camera 00" };`
to
`protected List<string> CameraNames = new List<string> { "GalaxyCamera", "Camera ScaledSpace", "UIMainCamera", "Camera 00" };`

![1](https://user-images.githubusercontent.com/22871614/89125238-a05e9400-d50f-11ea-9af5-d0f7d5f3baff.PNG)

P.S. My apologies for not bringing this change to attention sooner as I never played KSP 1.9.x in the first half of 2020 until recent.

**Closed as completed** 2020-09-04 21:01 UTC
